server:
  port: 6920

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/epidemic_new
    username: root
    password: root
  redis:
    host: localhost
    port: 6379

tencent:
  appId: 1308835562
  secretId: AKIDlPs8AzVpdGiy4xysiqnY8XijaDeu1vbp
  secretKey: 95kAvdEh5LOFyWs1ynwrZErJZcFtQp6B
  region: ap-guangzhou
  photoBucket: moss-1308835562



mybatis-plus:
  mapper-locations: classpath:mapper/*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
